-- Candidate-date holds and the manual booking workflow.
-- A request immediately holds every proposed date. Once one date is chosen,
-- the other holds are released and the selected date remains held while the
-- customer has 48 hours to pay.

-- Some early environments created admin_users before the role column was
-- introduced. Bring those databases in line with the current admin policy.
alter table public.admin_users
  add column if not exists role text not null default 'viewer';

alter table public.admin_users
  drop constraint if exists admin_users_role_check;

alter table public.admin_users
  add constraint admin_users_role_check
  check (role in ('viewer', 'editor'));

update public.admin_users
set role = 'editor'
where lower(email) = 'dev@awai-studio.jp';

alter table public.booking_requests
  add column if not exists selected_date date,
  add column if not exists selected_time time,
  add column if not exists payment_link_sent_at timestamptz,
  add column if not exists payment_due_at timestamptz;

alter table public.booking_requests
  drop constraint if exists booking_requests_selected_date_time_pair;

alter table public.booking_requests
  add constraint booking_requests_selected_date_time_pair
  check (
    (selected_date is null and selected_time is null)
    or (selected_date is not null and selected_time is not null)
  );

alter table public.booking_requests
  drop constraint if exists booking_requests_status_allowed;

alter table public.booking_requests
  add constraint booking_requests_status_allowed
  check (
    status in (
      'new',
      'contacted',
      'payment_pending',
      'confirmed',
      'cancelled',
      'expired'
    )
  );

create table if not exists public.booking_request_date_holds (
  id bigint generated by default as identity primary key,
  booking_request_id bigint not null
    references public.booking_requests(id) on delete cascade,
  experience_slug text not null,
  held_date date not null,
  held_time time not null,
  hold_kind text not null default 'candidate'
    check (hold_kind in ('candidate', 'payment_pending', 'confirmed')),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_request_date_holds_request_date_unique
    unique (booking_request_id, held_date),
  constraint booking_request_date_holds_one_per_day
    unique (experience_slug, held_date)
);

create index if not exists booking_request_date_holds_request_index
  on public.booking_request_date_holds (booking_request_id);

create index if not exists booking_request_date_holds_expiry_index
  on public.booking_request_date_holds (expires_at)
  where expires_at is not null;

create or replace function public.create_booking_request_candidate_holds()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  delete from public.booking_request_date_holds
  where expires_at is not null
    and expires_at <= now();

  if new.preferred_date_1 is not null then
    insert into public.booking_request_date_holds (
      booking_request_id,
      experience_slug,
      held_date,
      held_time
    ) values (
      new.id,
      new.experience_slug,
      new.preferred_date_1,
      new.preferred_time_1
    );
  end if;

  if new.preferred_date_2 is not null then
    insert into public.booking_request_date_holds (
      booking_request_id,
      experience_slug,
      held_date,
      held_time
    ) values (
      new.id,
      new.experience_slug,
      new.preferred_date_2,
      new.preferred_time_2
    );
  end if;

  if new.preferred_date_3 is not null then
    insert into public.booking_request_date_holds (
      booking_request_id,
      experience_slug,
      held_date,
      held_time
    ) values (
      new.id,
      new.experience_slug,
      new.preferred_date_3,
      new.preferred_time_3
    );
  end if;

  return new;
end;
$function$;

revoke all on function public.create_booking_request_candidate_holds()
  from public, anon, authenticated;

drop trigger if exists create_booking_request_candidate_holds
  on public.booking_requests;

create trigger create_booking_request_candidate_holds
  after insert on public.booking_requests
  for each row execute function public.create_booking_request_candidate_holds();

create or replace function public.manage_booking_request(
  p_request_id bigint,
  p_action text,
  p_selected_date date default null,
  p_selected_time time default null
)
returns public.booking_requests
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_request public.booking_requests%rowtype;
  v_payment_due_at timestamptz;
begin
  if not public.is_awai_admin('editor') then
    raise exception 'Administrator permission is required';
  end if;

  select * into v_request
  from public.booking_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception 'Booking request not found';
  end if;

  if p_action = 'select_date' then
    if v_request.status not in ('new', 'contacted') then
      raise exception 'This request is not waiting for date selection';
    end if;

    if not (
      (p_selected_date = v_request.preferred_date_1 and
       p_selected_time = v_request.preferred_time_1)
      or
      (p_selected_date = v_request.preferred_date_2 and
       p_selected_time = v_request.preferred_time_2)
      or
      (p_selected_date = v_request.preferred_date_3 and
       p_selected_time = v_request.preferred_time_3)
    ) then
      raise exception 'Select one of the requested date and time pairs';
    end if;

    v_payment_due_at := now() + interval '48 hours';

    delete from public.booking_request_date_holds
    where booking_request_id = p_request_id
      and held_date <> p_selected_date;

    insert into public.booking_request_date_holds (
      booking_request_id,
      experience_slug,
      held_date,
      held_time,
      hold_kind,
      expires_at
    ) values (
      p_request_id,
      v_request.experience_slug,
      p_selected_date,
      p_selected_time,
      'payment_pending',
      v_payment_due_at
    )
    on conflict (booking_request_id, held_date)
    do update set
      held_time = excluded.held_time,
      hold_kind = excluded.hold_kind,
      expires_at = excluded.expires_at,
      updated_at = now();

    update public.booking_requests
    set status = 'payment_pending',
        selected_date = p_selected_date,
        selected_time = p_selected_time,
        payment_link_sent_at = now(),
        payment_due_at = v_payment_due_at
    where id = p_request_id
    returning * into v_request;

  elsif p_action = 'confirm' then
    if v_request.status <> 'payment_pending' then
      raise exception 'This request is not waiting for payment';
    end if;

    if v_request.selected_date is null or v_request.selected_time is null then
      raise exception 'Select a booking date before confirming payment';
    end if;

    if v_request.payment_due_at is not null
       and v_request.payment_due_at <= now() then
      raise exception 'The payment deadline has passed';
    end if;

    delete from public.booking_request_date_holds
    where booking_request_id = p_request_id
      and held_date <> v_request.selected_date;

    insert into public.booking_request_date_holds (
      booking_request_id,
      experience_slug,
      held_date,
      held_time,
      hold_kind,
      expires_at
    ) values (
      p_request_id,
      v_request.experience_slug,
      v_request.selected_date,
      v_request.selected_time,
      'confirmed',
      null
    )
    on conflict (booking_request_id, held_date)
    do update set
      held_time = excluded.held_time,
      hold_kind = excluded.hold_kind,
      expires_at = null,
      updated_at = now();

    update public.booking_requests
    set status = 'confirmed',
        confirmed_date = selected_date,
        confirmed_time = selected_time,
        payment_due_at = null
    where id = p_request_id
    returning * into v_request;

  elsif p_action in ('cancel', 'expire') then
    delete from public.booking_request_date_holds
    where booking_request_id = p_request_id;

    update public.booking_requests
    set status = case
          when p_action = 'cancel' then 'cancelled'
          else 'expired'
        end,
        payment_due_at = null
    where id = p_request_id
    returning * into v_request;

  else
    raise exception 'Unsupported booking action';
  end if;

  return v_request;
end;
$function$;

revoke all on function public.manage_booking_request(
  bigint,
  text,
  date,
  time
) from public, anon;

grant execute on function public.manage_booking_request(
  bigint,
  text,
  date,
  time
) to authenticated;

alter table public.booking_request_date_holds enable row level security;

revoke all on table public.booking_request_date_holds
  from public, anon, authenticated;

grant select on table public.booking_request_date_holds to authenticated;

drop policy if exists "awai admins can read booking date holds"
  on public.booking_request_date_holds;

create policy "awai admins can read booking date holds"
  on public.booking_request_date_holds
  for select
  to authenticated
  using ((select public.is_awai_admin('viewer')));

notify pgrst, 'reload schema';
